# Generated by Django 2.2.16 on 2020-09-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
