# Generated by Django 2.2.16 on 2020-09-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_demomodel'),
        ('users', '0004_remove_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_hello', to='home.DemoModel'),
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
