# Generated by Django 2.2.16 on 2020-09-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
