# Generated by Django 2.2.16 on 2020-09-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_homepage_new_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="new_field",
        ),
        migrations.DeleteModel(
            name="Demo",
        ),
    ]
